import React, { useState } from 'react';
import Sidebar from '../components/Sidebar';
import ToothChart from '../components/ToothChart';
import ChatBox from '../components/ChatBox';
import DentalPieChart from '../components/DentalPieChart';
import jsPDF from "jspdf";

const DentistDashboard = ({ onLogout }) => {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [selectedPatient, setSelectedPatient] = useState('John Doe');

  const createDefaultChart = () => {
    return Array.from({ length: 32 }).reduce((acc, _, i) => {
      acc[i + 1] = 0;
      return acc;
    }, {});
  };

  const [patientDatabase, setPatientDatabase] = useState({
    'John Doe': { teeth: createDefaultChart(), bleeding: {} },
    'Jane Smith': { teeth: createDefaultChart(), bleeding: {} },
    'Alex Mercer': { teeth: createDefaultChart(), bleeding: {} },
  });

  const [currentTeethStates, setCurrentTeethStates] = useState(createDefaultChart());
  const [bleedingMap, setBleedingMap] = useState({});
  const [selectedTooth, setSelectedTooth] = useState(null);

  const [patientProfiles, setPatientProfiles] = useState({
  'John Doe': {
    age: 24,
    gender: 'Male',
    bloodGroup: 'O+',
    phone: '9876543210',
    appointment: '25 June 2025 - 10:00 AM',
  },

  'Jane Smith': {
    age: 30,
    gender: 'Female',
    bloodGroup: 'A+',
    phone: '9876543211',
    appointment: '26 June 2025 - 02:00 PM',
  },

  'Alex Mercer': {
    age: 27,
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '9876543212',
    appointment: '28 June 2025 - 11:30 AM',
  },
});

  const [selectedMode, setSelectedMode] = useState('cavity');

  const generateReport = () => {
  const doc = new jsPDF();

  // 🟣 HEADER
  doc.setFontSize(20);
  doc.setTextColor(128, 0, 128);
  doc.text("Dental Clinical Report", 20, 20);

  // ───────── PATIENT INFO ─────────
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);

  doc.text(`Patient: ${selectedPatient}`, 20, 40);
  doc.text(`Age: ${patientProfiles[selectedPatient].age}`, 20, 50);
  doc.text(`Gender: ${patientProfiles[selectedPatient].gender}`, 20, 60);
  doc.text(`Blood Group: ${patientProfiles[selectedPatient].bloodGroup}`, 20, 70);
  doc.text(`Phone: ${patientProfiles[selectedPatient].phone}`, 20, 80);

  // ───────── DENTAL DATA ─────────
  doc.setFontSize(13);
  doc.setTextColor(0, 102, 204);
  doc.text("Dental Summary", 20, 100);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);

  doc.text(`Healthy Teeth: ${healthyCount}`, 20, 115);
  doc.text(`Cavities: ${cavityCount}`, 20, 125);
  doc.text(`Filled Teeth: ${filledCount}`, 20, 135);

  doc.text(`Bleeding Score: ${totalBleeding}`, 20, 150);
  doc.text(`Risk Level: ${risk}`, 20, 160);

  // ───────── APPOINTMENT ─────────
  doc.setFontSize(12);
  doc.text(
    `Appointment: ${patientProfiles[selectedPatient].appointment}`,
    20,
    180
  );

  // ───────── FOOTER ─────────
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Generated by DentalClinic System", 20, 280);

  doc.save(`${selectedPatient}_report.pdf`);
};

  // 🦷 TOOTH CLICK
  const handleToothClick = (toothNum) => {
    setSelectedTooth(toothNum);

    setCurrentTeethStates((prev) => ({
      ...prev,
      [toothNum]:
        selectedMode === 'healthy'
          ? 0
          : selectedMode === 'cavity'
          ? 1
          : 2,
    }));
  };

  // 🩸 BLEEDING
  const handleBleedingChange = (value) => {
    if (!selectedTooth) return;

    setBleedingMap((prev) => ({
      ...prev,
      [selectedTooth]: value,
    }));
  };

  // 👤 PATIENT CHANGE
  const handlePatientChange = (e) => {
    const next = e.target.value;
    setSelectedPatient(next);

    setCurrentTeethStates(patientDatabase[next]?.teeth || createDefaultChart());
    setBleedingMap(patientDatabase[next]?.bleeding || {});
    setSelectedTooth(null);
  };

  // 📊 COUNTERS
  const healthyCount = Object.values(currentTeethStates).filter(s => s === 0).length;
  const cavityCount = Object.values(currentTeethStates).filter(s => s === 1).length;
  const filledCount = Object.values(currentTeethStates).filter(s => s === 2).length;

  const totalBleeding = Object.values(bleedingMap).reduce((a, b) => a + b, 0);

  let risk = "Low";
  if (totalBleeding > 25 || cavityCount > 6) risk = "High";
  else if (totalBleeding > 10 || cavityCount > 3) risk = "Medium";

  const handleSaveChanges = () => {
    setPatientDatabase((prev) => ({
      ...prev,
      [selectedPatient]: {
        teeth: currentTeethStates,
        bleeding: bleedingMap,
      },
    }));

    const scheduleAppointment = () => {
  const date = prompt("Enter appointment date and time");

  if (!date) return;

  setPatientProfiles(prev => ({
    ...prev,
    [selectedPatient]: {
      ...prev[selectedPatient],
      appointment: date,
    },
  }));
};

const rescheduleAppointment = () => {
  const date = prompt("Enter new appointment date and time");

  if (!date) return;

  setPatientProfiles(prev => ({
    ...prev,
    [selectedPatient]: {
      ...prev[selectedPatient],
      appointment: date,
    },
  }));
};

const cancelAppointment = () => {
  setPatientProfiles(prev => ({
    ...prev,
    [selectedPatient]: {
      ...prev[selectedPatient],
      appointment: "No appointment scheduled",
    },
  }));
};

    const generateReport = () => {
  const doc = new jsPDF();

  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("Dental Clinical Report", 20, 20);

  doc.setTextColor(0, 0, 0);

  doc.setFontSize(15);
  doc.text("Patient Information", 20, 45);

  doc.setFontSize(12);
  doc.text(`Patient: ${selectedPatient}`, 20, 60);
  doc.text(`Age: ${patientProfiles[selectedPatient].age}`, 20, 70);
  doc.text(`Gender: ${patientProfiles[selectedPatient].gender}`, 20, 80);
  doc.text(`Blood Group: ${patientProfiles[selectedPatient].bloodGroup}`, 20, 90);
  doc.text(`Phone: ${patientProfiles[selectedPatient].phone}`, 20, 100);

  doc.setFontSize(15);
  doc.text("Dental Summary", 20, 125);

  doc.setFontSize(12);
  doc.text(`Healthy Teeth: ${healthyCount}`, 20, 140);
  doc.text(`Cavities: ${cavityCount}`, 20, 150);
  doc.text(`Filled Teeth: ${filledCount}`, 20, 160);

  doc.setFontSize(15);
  doc.text("Clinical Assessment", 20, 185);

  doc.setFontSize(12);
  doc.text(`Bleeding Score: ${totalBleeding}`, 20, 200);
  doc.text(`Risk Level: ${risk}`, 20, 210);

  doc.setFontSize(15);
  doc.text("Appointment", 20, 235);

  doc.setFontSize(12);
  doc.text(
    `${patientProfiles[selectedPatient].appointment}`,
    20,
    250
  );

  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by DentalClub Management System",
    20,
    285
  );

  doc.save(`${selectedPatient}_report.pdf`);
};

    alert("Saved successfully ✔");
  };

  return (
    <div className="min-h-screen bg-slate-100 flex">

      {/* SIDEBAR */}
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />

      <main className="flex-1 p-6 space-y-6">

        {/* HEADER */}
        <div className="bg-gradient-to-r from-purple-600 to-pink-500 text-white p-6 rounded-xl">
          <h1 className="text-2xl font-bold">Dentist Dashboard</h1>
        </div>

        {/* PATIENT SELECT */}
        <div className="bg-white p-4 flex justify-between rounded-xl">
          <select
            value={selectedPatient}
            onChange={handlePatientChange}
            className="border p-2 rounded"
          >
            <option>John Doe</option>
            <option>Jane Smith</option>
            <option>Alex Mercer</option>
          </select>

          <button
            onClick={onLogout}
            className="bg-red-500 text-white px-4 py-2 rounded"
          >
            Logout
          </button>
        </div>

        {/* ================= DASHBOARD ================= */}
        {activeTab === 'dashboard' && (
          <>
            {/* MODE */}
            <div className="bg-white p-4 rounded-xl flex gap-3">
              <button
                onClick={() => setSelectedMode('healthy')}
                className={`px-3 py-2 rounded ${
                  selectedMode === 'healthy'
                    ? 'bg-green-600 text-white'
                    : 'bg-green-100'
                }`}
              >
                Healthy
              </button>

              <button
                onClick={() => setSelectedMode('cavity')}
                className={`px-3 py-2 rounded ${
                  selectedMode === 'cavity'
                    ? 'bg-pink-600 text-white'
                    : 'bg-pink-100'
                }`}
              >
                Cavity
              </button>

              <button
                onClick={() => setSelectedMode('filled')}
                className={`px-3 py-2 rounded ${
                  selectedMode === 'filled'
                    ? 'bg-blue-600 text-white'
                    : 'bg-blue-100'
                }`}
              >
                Filled
              </button>
            </div>

            {/* PROFILE */}
            <div className="bg-white p-5 rounded-xl shadow">
              <h2 className="font-bold mb-3">Patient Profile</h2>
              <p>Age: {patientProfiles[selectedPatient].age}</p>
              <p>Gender: {patientProfiles[selectedPatient].gender}</p>
              <p>Blood: {patientProfiles[selectedPatient].bloodGroup}</p>
              <p>Phone: {patientProfiles[selectedPatient].phone}</p>
            </div>

            {/* STATS */}
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-green-500 text-white p-4 rounded">
                Healthy: {healthyCount}
              </div>
              <div className="bg-pink-500 text-white p-4 rounded">
                Cavities: {cavityCount}
              </div>
              <div className="bg-blue-500 text-white p-4 rounded">
                Filled: {filledCount}
              </div>
            </div>

            <DentalPieChart
              healthy={healthyCount}
              cavity={cavityCount}
              filled={filledCount}
            />

            {/* BLEEDING */}
            <div className="bg-white p-4 rounded-xl">
              <h2 className="font-bold">Bleeding (1–5)</h2>

              {selectedTooth ? (
                <select
                  value={bleedingMap[selectedTooth] || 0}
                  onChange={(e) =>
                    handleBleedingChange(Number(e.target.value))
                  }
                  className="border p-2 rounded"
                >
                  <option value={0}>0</option>
                  <option value={1}>1</option>
                  <option value={2}>2</option>
                  <option value={3}>3</option>
                  <option value={4}>4</option>
                  <option value={5}>5</option>
                </select>
              ) : (
                <p className="text-gray-500">Select a tooth first</p>
              )}
            </div>

            <button
              onClick={handleSaveChanges}
              className="bg-indigo-600 text-white px-6 py-2 rounded"
            >
              💾 Save Changes
            </button>
            <button
  onClick={generateReport}
  className="bg-green-600 text-white px-6 py-2 rounded ml-3"
>
  📄 Download Report
</button>

            <div className="bg-white p-4 rounded-xl">
              <ToothChart
                teethStates={currentTeethStates}
                onToothClick={handleToothClick}
                selectedTooth={selectedTooth}
                bleedingMap={bleedingMap}
              />
            </div>
          </>
        )}

        {/* ================= CHATS ================= */}
        {activeTab === 'chats' && (
          <ChatBox />
        )}

       {/* ================= DENTAL CHART TAB ================= */}
{activeTab === 'dentalChart' && (
  <div className="space-y-6">

    {/* TITLE */}
    <div className="bg-white p-4 rounded-xl shadow">
      <h2 className="font-bold text-lg">Dental Analysis</h2>
      <p className="text-gray-500 text-sm">
        Visual breakdown of patient condition
      </p>
    </div>

    {/* PIE CHART (TOP) */}
    <div className="bg-white p-6 rounded-xl shadow flex justify-center">
      <DentalPieChart
        healthy={healthyCount}
        cavity={cavityCount}
        filled={filledCount}
      />
    </div>

    {/* STATS BELOW PIE CHART */}
    <div className="grid grid-cols-3 gap-4">
      <div className="bg-green-500 text-white p-4 rounded">
        Healthy: {healthyCount}
      </div>

      <div className="bg-pink-500 text-white p-4 rounded">
        Cavities: {cavityCount}
      </div>

      <div className="bg-blue-500 text-white p-4 rounded">
        Filled: {filledCount}
      </div>
    </div>

    {/* TOOTH CHART (BOTTOM) */}
    <div className="bg-white p-4 rounded-xl shadow">
      <h3 className="font-bold mb-3">Tooth Visualization</h3>

      <ToothChart
        teethStates={currentTeethStates}
        onToothClick={handleToothClick}
        selectedTooth={selectedTooth}
        bleedingMap={bleedingMap}
      />
    </div>

  </div>
)}

        {/* ================= REPORTS ================= */}
        {activeTab === 'reports' && (
          <div className="bg-white p-5 rounded-xl shadow">
            <h2 className="font-bold mb-3">Clinical Report</h2>

            <p>Healthy: {healthyCount}</p>
            <p>Cavities: {cavityCount}</p>
            <p>Filled: {filledCount}</p>
            <p>Bleeding Score: {totalBleeding}</p>
            <p>Risk: {risk}</p>

            <div className="mt-4">
              Appointment: {patientProfiles[selectedPatient].appointment}
            </div>
          </div>
        )}
        
        <button
  onClick={generateReport}
  className="mt-5 bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded"
>
  📄 Download PDF Report
</button>

      </main>
    </div>
  );
};

export default DentistDashboard;