import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import jsPDF from "jspdf";
import Sidebar from "../components/Sidebar";
import ToothChart from "../components/ToothChart";
import ChatBox from "../components/ChatBox";
import DentalPieChart from "../components/DentalPieChart";

const DentistDashboard = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("dashboard");
  const [selectedPatient, setSelectedPatient] = useState("John Doe");

  const createDefaultChart = () => {
    return Array.from({ length: 32 }).reduce((acc, _, i) => {
      acc[i + 1] = 0;
      return acc;
    }, {});
  };

  const [patientDatabase, setPatientDatabase] = useState({
    "John Doe": { teeth: createDefaultChart(), bleeding: {} },
    "Jane Smith": { teeth: createDefaultChart(), bleeding: {} },
    "Alex Mercer": { teeth: createDefaultChart(), bleeding: {} },
  });

  const [currentTeethStates, setCurrentTeethStates] = useState(createDefaultChart());
  const [bleedingMap, setBleedingMap] = useState({});
  const [selectedTooth, setSelectedTooth] = useState(null);

  const [patientProfiles] = useState({
    "John Doe": {
      age: 24,
      gender: "Male",
      bloodGroup: "O+",
      phone: "9876543210",
      appointment: "25 June 2025 - 10:00 AM",
    },
    "Jane Smith": {
      age: 30,
      gender: "Female",
      bloodGroup: "A+",
      phone: "9876543211",
      appointment: "26 June 2025 - 02:00 PM",
    },
    "Alex Mercer": {
      age: 27,
      gender: "Male",
      bloodGroup: "B+",
      phone: "9876543212",
      appointment: "28 June 2025 - 11:30 AM",
    },
  });

  const [selectedMode, setSelectedMode] = useState("cavity");

  const handleToothClick = (toothNum) => {
    setSelectedTooth(toothNum);

    setCurrentTeethStates((prev) => ({
      ...prev,
      [toothNum]:
        selectedMode === "healthy" ? 0 : selectedMode === "cavity" ? 1 : 2,
    }));
  };

  const handleBleedingChange = (value) => {
    if (!selectedTooth) return;

    setBleedingMap((prev) => ({
      ...prev,
      [selectedTooth]: value,
    }));
  };

  const handlePatientChange = (e) => {
    const next = e.target.value;
    setSelectedPatient(next);

    setCurrentTeethStates(patientDatabase[next]?.teeth || createDefaultChart());
    setBleedingMap(patientDatabase[next]?.bleeding || {});
    setSelectedTooth(null);
  };

  const healthyCount = Object.values(currentTeethStates).filter((s) => s === 0).length;
  const cavityCount = Object.values(currentTeethStates).filter((s) => s === 1).length;
  const filledCount = Object.values(currentTeethStates).filter((s) => s === 2).length;

  const totalBleeding = Object.values(bleedingMap).reduce((a, b) => a + b, 0);

  let risk = "Low";
  if (totalBleeding > 25 || cavityCount > 6) risk = "High";
  else if (totalBleeding > 10 || cavityCount > 3) risk = "Medium";

  const generateReport = () => {
    const doc = new jsPDF();
    const profile = patientProfiles[selectedPatient];

    doc.setFillColor(8, 145, 178);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("Dental Clinical Report", 20, 20);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(15);
    doc.text("Patient Information", 20, 45);

    doc.setFontSize(12);
    doc.text(`Patient: ${selectedPatient}`, 20, 60);
    doc.text(`Age: ${profile.age}`, 20, 70);
    doc.text(`Gender: ${profile.gender}`, 20, 80);
    doc.text(`Blood Group: ${profile.bloodGroup}`, 20, 90);
    doc.text(`Phone: ${profile.phone}`, 20, 100);

    doc.setFontSize(15);
    doc.text("Dental Summary", 20, 125);

    doc.setFontSize(12);
    doc.text(`Healthy Teeth: ${healthyCount}`, 20, 140);
    doc.text(`Cavities: ${cavityCount}`, 20, 150);
    doc.text(`Filled Teeth: ${filledCount}`, 20, 160);

    doc.setFontSize(15);
    doc.text("Clinical Assessment", 20, 185);

    doc.setFontSize(12);
    doc.text(`Bleeding Score: ${totalBleeding}`, 20, 200);
    doc.text(`Risk Level: ${risk}`, 20, 210);

    doc.setFontSize(15);
    doc.text("Appointment", 20, 235);

    doc.setFontSize(12);
    doc.text(`${profile.appointment}`, 20, 250);

    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text("Generated by DentalClub Management System", 20, 285);

    doc.save(`${selectedPatient}_report.pdf`);
    toast.success("PDF report downloaded!");
  };

  const handleSaveChanges = () => {
    setPatientDatabase((prev) => ({
      ...prev,
      [selectedPatient]: {
        teeth: currentTeethStates,
        bleeding: bleedingMap,
      },
    }));

    toast.success("Changes saved successfully!");
  };

  return (
    <div className="flex min-h-screen bg-slate-100">
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />

      <main className="flex-1 space-y-6 p-6">
        <div className="rounded-xl bg-gradient-to-r from-cyan-600 to-teal-500 p-6 text-white">
          <h1 className="text-2xl font-bold">Dentist Dashboard</h1>
        </div>

        <div className="flex justify-between rounded-xl bg-white p-4">
          <select
            value={selectedPatient}
            onChange={handlePatientChange}
            className="rounded border p-2"
          >
            <option>John Doe</option>
            <option>Jane Smith</option>
            <option>Alex Mercer</option>
          </select>

          <button
            onClick={() => navigate("/")}
            className="rounded bg-red-500 px-4 py-2 text-white"
          >
            Logout
          </button>
        </div>

        {activeTab === "dashboard" && (
          <>
            <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
              <div className="rounded-2xl border bg-white p-4 shadow-sm">
                <p className="text-sm text-slate-500">Today&apos;s Appointments</p>
                <p className="text-2xl font-bold text-slate-800">4</p>
              </div>
              <div className="rounded-2xl border bg-white p-4 shadow-sm">
                <p className="text-sm text-slate-500">Pending Reports</p>
                <p className="text-2xl font-bold text-slate-800">2</p>
              </div>
              <div className="rounded-2xl border bg-white p-4 shadow-sm">
                <p className="text-sm text-slate-500">New Messages</p>
                <p className="text-2xl font-bold text-slate-800">3</p>
              </div>
              <div className="rounded-2xl border bg-white p-4 shadow-sm">
                <p className="text-sm text-slate-500">Patients This Week</p>
                <p className="text-2xl font-bold text-slate-800">18</p>
              </div>
            </div>

            <div className="flex gap-3 rounded-xl bg-white p-4">
              <button
                onClick={() => setSelectedMode("healthy")}
                className={`rounded px-3 py-2 ${
                  selectedMode === "healthy" ? "bg-green-600 text-white" : "bg-green-100"
                }`}
              >
                Healthy
              </button>
              <button
                onClick={() => setSelectedMode("cavity")}
                className={`rounded px-3 py-2 ${
                  selectedMode === "cavity" ? "bg-pink-600 text-white" : "bg-pink-100"
                }`}
              >
                Cavity
              </button>
              <button
                onClick={() => setSelectedMode("filled")}
                className={`rounded px-3 py-2 ${
                  selectedMode === "filled" ? "bg-blue-600 text-white" : "bg-blue-100"
                }`}
              >
                Filled
              </button>
            </div>

            <div className="rounded-xl bg-white p-5 shadow">
              <h2 className="mb-3 font-bold">Patient Profile</h2>
              <p>Age: {patientProfiles[selectedPatient].age}</p>
              <p>Gender: {patientProfiles[selectedPatient].gender}</p>
              <p>Blood: {patientProfiles[selectedPatient].bloodGroup}</p>
              <p>Phone: {patientProfiles[selectedPatient].phone}</p>
              <p className="mt-2 text-cyan-700">
                Next visit: {patientProfiles[selectedPatient].appointment}
              </p>
            </div>

            <div className="grid grid-cols-3 gap-4">
              <div className="rounded bg-green-500 p-4 text-white">
                Healthy: {healthyCount}
              </div>
              <div className="rounded bg-pink-500 p-4 text-white">
                Cavities: {cavityCount}
              </div>
              <div className="rounded bg-blue-500 p-4 text-white">
                Filled: {filledCount}
              </div>
            </div>

            <DentalPieChart
              healthy={healthyCount}
              cavity={cavityCount}
              filled={filledCount}
            />

            <div className="rounded-xl bg-white p-4">
              <h2 className="font-bold">Bleeding (1–5)</h2>
              {selectedTooth ? (
                <select
                  value={bleedingMap[selectedTooth] || 0}
                  onChange={(e) => handleBleedingChange(Number(e.target.value))}
                  className="mt-2 rounded border p-2"
                >
                  <option value={0}>0</option>
                  <option value={1}>1</option>
                  <option value={2}>2</option>
                  <option value={3}>3</option>
                  <option value={4}>4</option>
                  <option value={5}>5</option>
                </select>
              ) : (
                <p className="mt-2 text-gray-500">Select a tooth first</p>
              )}
            </div>

            <div>
              <button
                onClick={handleSaveChanges}
                className="rounded bg-indigo-600 px-6 py-2 text-white"
              >
                Save Changes
              </button>
              <button
                onClick={generateReport}
                className="ml-3 rounded bg-green-600 px-6 py-2 text-white"
              >
                Download Report
              </button>
            </div>

            <div className="rounded-xl bg-white p-4">
              <ToothChart
                teethStates={currentTeethStates}
                onToothClick={handleToothClick}
                selectedTooth={selectedTooth}
                bleedingMap={bleedingMap}
              />
            </div>
          </>
        )}

        {activeTab === "chats" && <ChatBox />}

        {activeTab === "dentalChart" && (
          <div className="space-y-6">
            <div className="rounded-xl bg-white p-4 shadow">
              <h2 className="text-lg font-bold">Dental Analysis</h2>
              <p className="text-sm text-gray-500">Visual breakdown of patient condition</p>
            </div>

            <div className="flex justify-center rounded-xl bg-white p-6 shadow">
              <DentalPieChart
                healthy={healthyCount}
                cavity={cavityCount}
                filled={filledCount}
              />
            </div>

            <div className="grid grid-cols-3 gap-4">
              <div className="rounded bg-green-500 p-4 text-white">
                Healthy: {healthyCount}
              </div>
              <div className="rounded bg-pink-500 p-4 text-white">
                Cavities: {cavityCount}
              </div>
              <div className="rounded bg-blue-500 p-4 text-white">
                Filled: {filledCount}
              </div>
            </div>

            <div className="rounded-xl bg-white p-4 shadow">
              <h3 className="mb-3 font-bold">Tooth Visualization</h3>
              <ToothChart
                teethStates={currentTeethStates}
                onToothClick={handleToothClick}
                selectedTooth={selectedTooth}
                bleedingMap={bleedingMap}
              />
            </div>
          </div>
        )}

        {activeTab === "reports" && (
          <>
            <div className="rounded-xl bg-white p-5 shadow">
              <h2 className="mb-3 font-bold">Clinical Report</h2>
              <p>Healthy: {healthyCount}</p>
              <p>Cavities: {cavityCount}</p>
              <p>Filled: {filledCount}</p>
              <p>Bleeding Score: {totalBleeding}</p>
              <p>Risk: {risk}</p>
              <div className="mt-4">
                Appointment: {patientProfiles[selectedPatient].appointment}
              </div>
            </div>

            <button
              onClick={generateReport}
              className="rounded bg-green-600 px-5 py-2 text-white hover:bg-green-700"
            >
              Download PDF Report
            </button>
          </>
        )}
      </main>
    </div>
  );
};

export default DentistDashboard;